---
id: 1
name: Punch
level_req: 1
damage: 1
for_player: True
---
id: 2
name: Kick
level_req: 1
damage: 10
for_player: True
---
id: 3
name: Jab
level_req: 1
damage: 10
for_player: False
---
id: 4
name: Karate Chop
level_req: 2
damage: 50
for_player: True
